"""empty message

Revision ID: 4b3e82698eef
Revises: 111797cf14fd
Create Date: 2018-03-28 20:01:59.932311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3e82698eef'
down_revision = '111797cf14fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('source', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'source')
    # ### end Alembic commands ###
