"""empty message

Revision ID: 6e3d3e107066
Revises: d259b3dd81c3
Create Date: 2018-03-27 17:53:49.636556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3d3e107066'
down_revision = 'd259b3dd81c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('image_upload', sa.Text(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'image_upload')
    # ### end Alembic commands ###
