"""empty message

Revision ID: a5fd4ec9ac7f
Revises: 445c4db6b65e
Create Date: 2018-03-26 11:54:49.663698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fd4ec9ac7f'
down_revision = '445c4db6b65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('published_on', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'published_on')
    # ### end Alembic commands ###
