"""empty message

Revision ID: d259b3dd81c3
Revises: 77da61da5a83
Create Date: 2018-03-27 02:40:37.466691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd259b3dd81c3'
down_revision = '77da61da5a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('category', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'category')
    # ### end Alembic commands ###
